- name: install depencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - jq
    - bc

- name: clone sources
  git:
    repo: https://github.com/sanpii/vmc.git
    dest: ~/vmc

- name: copy configuration
  copy:
    src: vmc
    dest: ~/.config/

- name: add current user to gpio group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    group: gpio
    append: yes

- name: install vmc service
  become: true
  template:
    src: files/vmc.service.j2
    dest: /etc/systemd/system/vmc.service

- name: start vmc service
  become: true
  service:
    name: vmc
    enabled: yes
    state: started
