- name: install git
  become: true
  package:
    name: git
    state: present

- name: clone sources
  git:
    repo: https://github.com/sanpii/vmc.git
    dest: ~/vmc

- name: copy configuration
  copy:
    src: vmc
    dest: ~/.config/

- name: install vmc service
  become: true
  copy:
    src: vmc.service
    dest: /etc/systemd/system

- name: start vmc service
  become: true
  service:
    name: vmc
    enabled: yes
    state: started
