- name: install postgresql
  become: true
  package:
    name: postgresql
    state: present

- name: install psycopg2
  become: true
  package:
    name: python-psycopg2
    state: present

- name: create vagrant user
  become: true
  become_user: postgres
  postgresql_user:
    name: vagrant
    password: vagrant
    role_attr_flags: SUPERUSER

- name: create domotic database
  become: true
  become_user: postgres
  postgresql_db:
    name: domotic
    owner: vagrant
