- name: install mosquitto utils
  become: true
  apt:
    name: mosquitto-clients
    state: present

- name: install mosquitto server
  become: true
  apt:
    name: mosquitto
    state: present

- name: copy websockets configuration
  become: true
  copy:
    src: websockets.conf
    dest: /etc/mosquitto/conf.d/
