#!/bin/bash

set -e

if [[ ! -e ~/.config/vmc ]]
then
    >&2 echo 'No configuration found'
    exit 1
else
    . ~/.config/vmc
fi

function main()
{
    listem_mqtt_weather
}

function listem_mqtt_weather()
{
    local humidity=0

    while read TOPIC STATE
    do
        humidity=$(current_humidity)

        if [[ $(comp "$humidity" '>=' '0.05') ]]
        then
            mosquitto_pub --username "$MQTT_USER" --pw "$MQTT_PASSWORD" \
                --qos 2 --topic domotic/vmc/state --message pulse2
        fi
    done < <(mosquitto_sub --username "$MQTT_USER" --pw "$MQTT_PASSWORD" --verbose --topic domotic/weather)
}

function current_humidity()
{
    psql domotic --no-psqlrc --tuples-only --command \
        "SELECT ROUND(regr_slope(humidity, EXTRACT(epoch FROM created))::numeric, 4) FROM humidity WHERE room_id=1 AND created >= now() - '10min'::interval;"
}

function comp()
{
    local a=$1
    local op=$2
    local b=$3

    if [[ $(echo "$a $op $b" | bc) -eq 1 ]]
    then
        echo true
    fi
}

main
