- name: modify boot cmdline
  become: true
  replace:
    dest: /boot/cmdline.txt
    regexp: 'console: ttyAMA0,115200 kgdboc: ttyAMA0,115200'
    replace: ''
  with_first_found:
    - files: [/dev/ttyAMA0]
      skip: true

- name: modify inittab
  become: true
  lineinfile:
    dest: /etc/inittab
    line: 'T0:23:respawn:/sbin/getty -L ttyAMA0 115200 vt100'
    state: absent
  with_first_found:
    - files: [/dev/ttyAMA0]
      skip: true

- name: configure serial port
  become: true
  command: stty 1200 cs7 evenp cstopb -igncr -inlcr -brkint -icrnl -opost -isig -icanon -iexten -F /dev/ttyAMA0
  with_first_found:
    - files: [/dev/ttyAMA0]
      skip: true

- name: install git
  become: true
  package:
    name: git
    state: present

- name: clone teleinfo
  git:
    repo: https://github.com/sanpii/domotic-teleinfo.git
    dest: ~/teleinfo

- name: compile teleinfo
  command: cargo build --release
  args:
    chdir: ~/teleinfo
    creates: ~/teleinfo/target/release/teleinfo

- name: install cron task
  become: true
  copy:
    src: cron
    dest: /etc/cron.d/teleinfo
