- name: add dotdeb repository key
  become: true
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: add dotdeb apt repository
  become: true
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ jessie main'
    state: present
    filename: dotdeb
