- name: install subversion
  become: true
  apt: name=subversion state=present

- name: install gcc
  become: true
  apt: name=gcc state=present

- name: clone open2300
  subversion: repo=http://www.lavrsen.dk/svn/open2300/trunk/ dest=~/open2300

- name: copy json2300.c
  copy: src=json2300.c dest=~/open2300/

- name: compile open2300
  command: gcc -Wall -O3 -DVERSION="1.11" -lm json2300.c rw2300.c linux2300.c -o json2300
  args:
    chdir: ~/open2300
    creates: json2300

- name: install cron task
  become: true
  copy: src=cron dest=/etc/cron.d/json2300
