- name: install git
  become: true
  apt:
    name: git
    state: present

- name: clone ws2300
  git:
    repo: https://github.com/sanpii/ws2300.git
    dest: ~/ws2300

- name: compile ws2300
  command: cargo build --release
  args:
    chdir: ~/ws2300
    creates: ~/ws2300/target/release/ws2300

- name: install cron task
  become: true
  copy:
    src: cron
    dest: /etc/cron.d/ws2300
