- name: clone sources
  git: repo=https://github.com/sanpii/pg4grafana.git dest=~/pg4grafana

- name: copy configuration
  copy: src=parameters.yml dest=~/pg4grafana/app/config

- name: install composer
  become: true
  shell: wget https://getcomposer.org/installer -O - | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- composer: command=install working_dir=pg4grafana

- name: copy vhost
  become: true
  copy: src=pg4grafana.vhost dest=/etc/nginx/sites-enabled/
  notify: nginx reload
